export const plans = [
    {
      id: "0",
      title: "Gratuito",
      priceMonthly: 0,
      priceYearly: 0,
      caption: " ",
      features: [
        "Beneficio 1",
        "Beneficio 2",
        "Beneficio 3",
        "Beneficio 4",
        "Beneficio 5",
        "Beneficio 6",
      ],
    },
    {
        id: "1",
        title: "Básico",
        priceMonthly: 25,
        priceYearly: 260,
        caption: " ",
        features: [
          "Beneficio 1",
          "Beneficio 2",
          "Beneficio 3",
          "Beneficio 4",
          "Beneficio 5",
          "Beneficio 6",
        ],
      },
      {
        id: "2",
        title: "Premium",
        priceMonthly: 45,
        priceYearly: 400,
        caption: " ",
        features: [
          "Beneficio 1",
          "Beneficio 2",
          "Beneficio 3",
          "Beneficio 4",
          "Beneficio 5",
          "Beneficio 6",
        ],
      },
      {
        id: "3",
        title: "Black",
        priceMonthly: 65,
        priceYearly: 599,
        caption: " ",
        features: [
          "Beneficio 1",
          "Beneficio 2",
          "Beneficio 3",
          "Beneficio 4",
          "Beneficio 5",
          "Beneficio 6",
        ],
      },
  ];